services:
  - type: web
    name: edu-mate
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c \"import database; database.init_db(); database.seed_reference_data()\" && python esli_00.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: edu-mate-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 7861
      - key: HOST
        value: "0.0.0.0"
      - key: RENDER
        value: "true"

  - type: pserv
    name: edu-mate-db
    env: postgres
    postgres:
      version: "14"
